version: '3'
volumes:
  mysql-data:
    driver: local
  mysql-log:
    driver: local
  mysql-conf:
    driver: local

services:
  db:
    image: mysql
    networks: 
      - backend
    ports:
      - 3306:3306
    volumes:
      - ./codigo-fonte/mysql/database_schema.sql:/docker-entrypoint-initdb.d/dump.sql
      - "mysql-data:/var/lib/mysql"
      - "mysql-log:/var/log/mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: notes-api
      MYSQL_PASSWORD: notes-api
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  app:
    build: ./codigo-fonte/app/
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: 'db'
  proxy:
    image: nginx:latest
    volumes:
      - ./codigo-fonte/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - db
      - app
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge